/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _INCLUDE_ZEPHYR_DT_BINDINGS_CLOCK_IMX95_CLOCK_H_
#define _INCLUDE_ZEPHYR_DT_BINDINGS_CLOCK_IMX95_CLOCK_H_

#define IMX95_CLK_LPUART3 142

#endif /* _INCLUDE_ZEPHYR_DT_BINDINGS_CLOCK_IMX95_CLOCK_H_ */
