/*
 * Copyright 2023 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MCUX_CCM_REV3_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MCUX_CCM_REV3_H_

#define IMX_CCM_FLAG_NONE 0
#define IMX_CCM_FLAG_ASSUME_ON 1


#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_MCUX_CCM_REV3_H_ */
